import ClientOnly from "@/components/ClientOnly";
import Footer from "@/components/nav/Footer";
import Navbar from "@/components/nav/Navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "User App",
  description: "Generated by Tareq",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div>
        <ClientOnly>
          <div className="fixed top-0 w-screen ">
            <Navbar />
          </div>
        </ClientOnly>
        <div className=" h-auto pt-[70px] ">
          <hr />
          {children}
        </div>
        <Footer SITEMAP={[]} currentYear={0} />
      </div>
    </>
  );
}

/*

<div>
      <Navbar />
      <div className=" pt-12 ">{children}</div>
      <Footer />
    </div>
 <ClientOnly>
        <RentModel />
        <LoginModel />
        <RegisterModel />
        /* <Model actionLabel="Submit" title="hello world" isOpen /> */

/* <Navbar /> */

//   </ClientOnly>
