import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import Providers from "@/lib/Providers";
// import { Provider } from "react-redux";
// import { store } from "@/redux/store";
const font = Nunito({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Booking App",
  description: "Generated by Tareq",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

// import { Provider } from "react-redux";
