import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by Tareq",
};

const DashBoardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
    // <div className=" flex ">
    //   <div className=" w-full ">{children}</div>
    // </div>
  );
};

export default DashBoardLayout;
