"use client";
import SideBar from "@/components/dashboard/SideBar";
import { getUserInfo, isLoggedIn } from "@/utils/auth.service";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
// export const metadata: Metadata = {
//   title: "Dashboard App",
//   description: "Generated by Tareq",
// };

const DashBoardLayout = ({ children }: { children: React.ReactNode }) => {
  //=======================================================
  const userInfo: any = getUserInfo();
  const isAdmin = userInfo?.role === "admin";

  const router = useRouter();
  const userLoggedIn = isLoggedIn();
  const [isLoading, setIsLoading] = useState<boolean>(false);

  useEffect(() => {
    if (!userLoggedIn || !isAdmin) {
      router.push("/login");
    }
    setIsLoading(true);
  }, [router, isLoading, userLoggedIn, isAdmin]);

  if (!isLoading) {
    return (
      <div>
        <h1>Loading..........</h1>
      </div>
    );
  }

  //====================================================
  return (
    // <html lang="en">
    //   <body>{children}</body>
    // </html>
    <div className=" flex bg-gray-200 ">
      <div className=" w-[20%] h-full bg-gray-200 ">
        <SideBar />
      </div>
      <hr className=" h-screen w-[2px] bg-gray-700 " />
      <div className=" w-full bg-white px-10 py-8 ">{children}</div>
    </div>
  );
};

export default DashBoardLayout;
