import SideBar from "@/components/dashboard/SideBar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard App",
  description: "Generated by Tareq",
};

const DashBoardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    // <html lang="en">
    //   <body>{children}</body>
    // </html>
    <div className=" flex ">
      <div className=" w-[20%] h-screen bg-slate-400  ">
        <SideBar />
      </div>
      <div className=" w-full bg-red-300 ">{children}</div>
    </div>
  );
};

export default DashBoardLayout;
